# Generated by Django 3.0.2 on 2025-02-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_remove_ingredient_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredients',
            new_name='RecipeIngredient',
        ),
    ]
